# This is a basic workflow to help you get started with Actions

name: Generate keymap svg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  conditional_job:
    runs-on: ubuntu-latest
    outputs:
      output_keymap_changed: ${{ steps.check_keymap_changed.outputs.keymap_changed }}
    # Declare outputs for next jobs
    steps:
    - uses: actions/checkout@v4
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - run: echo HasChanged=${git diff --name-only HEAD HEAD~1} >> $GITHUB_ENV
    - id: check_keymap_changed
      run: echo "keymap_changed=${{ env.HasChanged }}" >> "$GITHUB_OUTPUT"
  add_keymap:
    runs-on: ubuntu-latest
    needs: conditional_job
    if: ${{ needs.conditional_job.outputs.output_keymap_changed }} == 'config/corne.keymap'
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "github-action@users.noreply.github.com"
      - run: git config --global user.name github-actions[bot]
      - name: Prepare python
        uses: actions/setup-python@v5
        with:
            python-version: 3.12
      - name: Install keymap drawer
        run: |
            python3 -m pip install keymap-drawer
      - run: rm keymap_image.svg
        continue-on-error: true
      - run: keymap parse -c 12 -z ${GITHUB_WORKSPACE}/config/corne.keymap > corne_keymap.yaml
      - run: keymap draw corne_keymap.yaml > keymap_image.svg
      - run: rm corne_keymap.yaml
      - name: Check for changes
        run: git status
      - name: Stage changed files
        run: git add keymap_image.svg
      - name: Commit changed files
        run: git commit -m "[BOT] Generate keymap svg."
      - name: Fetch from master
        run: git fetch origin main
      - name: Push code to main
        run: git push origin HEAD:main
